### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String java.lang.ThreadGroup.getName()' on a null object reference

### ISSUE THREAD

**Issue by Veeresh8** [s1rius/android-thread-inspector#6]
I'm using a thread pool executor and get the following crash when I run the app 

```

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.ThreadGroup.getName()' on a null object reference
        at java.lang.Thread.toString(Thread.java:1108)
        at java.lang.StringBuilder.append(StringBuilder.java:202)
        at me.weishu.epic.art.entry.Entry64.referenceBridge(Entry64.java:188)
        at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:526)
        at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:583)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:896)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
```

Any idea what can be done here?

**Comment by s1rius** [comment]
Sorry for delay,
We migrate from epic to [bhook](https://github.com/bytedance/bhook), if the crash present in new version, feel free to reopen this issue.
